apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-z3pw
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0030-tenant/tkrw-pr712-0075-0030-app/devfile-sample-z3pw@sha256:94873b2f7b60ea90773f92f89abc29dd7c79eb65be94d4e75c77e00f6c087dab
        name: my-nodejs
        resources: {}
status: {}
